### ISSUE TITLE
Fix messaging

### ISSUE THREAD

**Issue by YanaHor** [OlegPapka2/DevPlatform#13]
When you write long message without whitespaces, it doesn't wrap on new lines and just extends to right side with scrollbar below.
![зображення](https://user-images.githubusercontent.com/103226065/205147038-005b01e8-fbcc-4375-b12d-7dedcf533f9b.png)
![зображення](https://user-images.githubusercontent.com/103226065/205147074-859840d3-a396-49a3-8af6-29e90a0e7835.png)
![зображення](https://user-images.githubusercontent.com/103226065/205147108-04d30001-c26f-42c3-8b26-feeb5fc96df5.png)

**Comment by OlegPapka2** [comment]
@YanaHor seems fixed for me, check it out at 51c1684
