### ISSUE TITLE
Fix profile image

### ISSUE THREAD

**Issue by YanaHor** [OlegPapka2/DevPlatform#14]
You can add for profile image some file which doesn't support image.
![зображення](https://user-images.githubusercontent.com/103226065/205154514-02e2c5b5-2c32-40da-b5b7-5df00f4528c6.png)
![зображення](https://user-images.githubusercontent.com/103226065/205154119-1c5847bd-6a80-4fc1-abcc-c367901aed09.png)

**Comment by OlegPapka2** [comment]
## Profile editing
- [ ] Add file checks on Frontend and Backend.
- [ ] Throw an error on the wrong file provided.

Supported files should be: `.png`, `.jpg`, and `.jpeg`.

**Comment by OlegPapka2** [comment]
@YanaHor seems fixed to me, check it out, please :>
